### PR TITLE
Simulation half done

### PR DESCRIPTION
**Pull request by bchen290**
Simulation now shows a triangle with a point showing the robot and dashed lines connected to the robot

### CODE REVIEW

**Comment by HenryDangPRG** [comment]
You have unnecessary commits that can be squashed.
Please squash your commits. 

In addition, `Robot` is redundant, because `Ghost` is what you should have used. Move your changes over to `Ghost`.

**Comment by HenryDangPRG** [comment]
You have unnecessary commits that can be squashed.
Please squash your commits. 

In addition, `Robot` is redundant, because `Ghost` is what you should have used. Move your changes over to `Ghost`.

**Comment by bchen290** [comment]
I did everything as you said

**Comment by HenryDangPRG** [comment]
Squash the "Fix merge commit" please.

**Pull request closed without merging**
